### ISSUE TITLE
fields padding needs to be taken care of in sizeOf calculation

### ISSUE THREAD

**Issue by smunix** [jmorag/mcc#11]
https://github.com/jmorag/mcc/blob/cc37bd59415c4bfef76df715e38f608c26a07766/src/Microc/Codegen.hs#L104

https://en.wikipedia.org/wiki/Data_structure_alignment#Computing_padding

**Comment by jmorag** [comment]
https://github.com/jmorag/mcc/blob/master/src/Microc/Codegen.hs#L87-L91

I've been using packed structs to avoid having to do this computation. I know it's worse for performance but it's much easier to implement.

**Comment by smunix** [comment]
That makes sense, thanks! Closing this issue!
