### ISSUE TITLE
Booleans are 8 bits

### ISSUE THREAD

**Issue by smunix** [jmorag/mcc#12]
https://github.com/jmorag/mcc/blob/cc37bd59415c4bfef76df715e38f608c26a07766/src/Microc/Codegen.hs#L78

```haskell
TyBool -> pure AST.i8
```

**Comment by jmorag** [comment]
Why should booleans be 8 bits?

**Comment by smunix** [comment]
For performance reason, reading a single bit isn't efficient. But I guess, this is a design decision of yours. Great project btw ! It's refreshing to read your blog posts too.

**Comment by smunix** [comment]
came to think about this, int1 is probably the best choice for bools, indeed. Ignore my previous comments pls
